### ISSUE TITLE
GUIの提供

### ISSUE THREAD

**Issue by Hidetomi** [nttcom/metemcyber#22]
コマンドラインの操作が苦手な人向けにGUIを提供すると良いと考えました。
ぜひ、ご検討をお願いいたします。

**Comment by mshim03** [comment]
ご提案ありがとうございます。
内部でも検討中でして、開発体制の拡充後に開発タスクに積んでいく予定となります。

**Comment by nitky** [comment]
社内の開発支援プログラムへ応募。開発チームとしても非常に気になっている問題であるため、採択された場合は実装の優先度を可能な限り上げる予定です:pray:
