### ISSUE TITLE
PROVIDER_PORT変数の空文字判定

### ISSUE THREAD

**Issue by Hidetomi** [nttcom/metemcyber#23]
以下は、 ` if [ -n "${PROVIDER_PORT}" ]; then`が正しいかと思われます。

https://github.com/nttcom/metemcyber/blob/200608fac78d3abeff3c7364d0c93e340b7cacfc/metemcyber_ctl.sh#L224

**Comment by mshim03** [comment]
ご指摘ありがとうございます。対応いたしました
