### ISSUE TITLE
https://exchange.metemcyber.ntt.comにアクセスした結果、Access Deniedが返される

### ISSUE THREAD

**Issue by Hidetomi** [nttcom/metemcyber#27]
### 起きた事象

- 新規CTIトークンの配布、チャレンジ受付を開始後
`https://exchange.metemcyber.ntt.com `に`curl`でアクセスした結果、`Access Denied`が返される。
ブラウザでアクセスした場合も同様。

```
$ curl https://exchange.metemcyber.ntt.com 
{"error":"Access Denied"}
```

### 期待する動作

- 成功したかどうか判断がつくレスポンスメッセージが得られること。
- `Access Debued`の場合、どのようなアクションを起こすべきか判断が出来る情報。

### 実行環境（ホスト）

- OS
```
SystemDirectory : C:\Windows\system32
Organization    :
BuildNumber     : 19041
RegisteredUser  : owner
Version         : 10.0.19041
```

### 実行環境（Hypter-V ゲスト）

- OS

```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### gitハッシュ値

```
$ git rev-parse HEAD
a50f7e82d068828c1f8bca7276c51cbaad9414a0
```

### ログ等

事象発生時のブラウザ

```
$ curl https://exchange.metemcyber.ntt.com 
{"error":"Access Denied"}
```

**Comment by mshim03** [comment]
`https://exchange.metemcyber.ntt.com` にブラウザやcurlで直接アクセスすることは想定しておらず、
metemcyber のクライアントプログラム内でのみアクセスすることを想定しております。    
(具体的には、[gcs_solver.py](https://github.com/nttcom/metemcyber/blob/main/src/plugins/gcs_solver.py) 内からアクセス)  

チャレンジの動作をチェックする場合は、自分自身に対してチャレンジを実行するなどの方法で  
ご確認いただければと思います。

**Comment by Hidetomi** [comment]
ご回答ありがとうございます。動作仕様を把握しました。
