### ISSUE TITLE
コントラクト関数の返り値取得手法の確立

### ISSUE THREAD

**Issue by soum-kazuaki** [nttcom/metemcyber#29]
コントラクト関数の実行結果をブロックチェーン外から取得するには、返り値を call() でエミュレートするか、返り値をイベントとして emit するしかない（はず？）。ほとんどの場合は call() で問題ないが、ひとつのブロックに同じ関数のトランザクションが複数取り込まれた場合、期待する値が得られない可能性がある。

- web3 の call() ではブロックを番号・ハッシュで指定できるが、transactionIndex は指定できない。すなわち、当該ブロックで最も若いトランザクションの結果しか得られない。

現在の実装では、トランザクションを投入した後は waitForTransactionReceipt() を実行しており、投入したトランザクションがブロックに取り込まれるまで待機している。したがって、クライアント単体では問題は発生しない。しかしながら、複数クライアントが稼働する現状において、上記の問題は発生しうる。

この問題に抵触しそうな機能として「チャレンジ実行後のタスク番号取得」が挙げられる。ただ、この機能で取得するデータは（やや語弊があるが）アカウント毎に独立しているため、現実に不具合が生じることはないと考えられる。とは言え、今後の改修で単一アカウントで複数プログラムを並列実行するようなことになれば、上記の問題が発現する可能性がある。

コントラクト関数を実行して返り値を取得する、という手法の確立が望まれる。

- 補足
  チャレンジ開始はコントラクト関数でなく、ERC777Recipient を利用した「トークンの送付」をトリガーとして開始される。単なる関数実行とは、また少し違った対応が必要と思われる。

**Comment by nitky** [comment]
現状では、適切な方法が不明。必要になった時に再度検討。
